version: "3.8"
services:
    build-backend:
      build: ./backend
      ports:
        - "4000:4000"
      depends_on:
        - db

    build-frontend:
      build: ./frontend
      ports:
        - "3000:5173"

    db :
      image : mongo:7
      ports:
        - "27017:27017"
